[project]
name = "adventofcode2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask>=2024.12.0",
    "duckdb>=1.1.3",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
]

